### House Price Prediction Project
1. Project Definition:
- Goal: predict the sales price for each house

2.Feauture Selection:
- Choose feature to train ML model
- Need to use `Feature Engineering` to identify Features needed

3.Spliting the datasets
- `data`: dataset
- `x`: `data[feature]`
- `y` : target variable `SalePrice`

4. Training machine learning model

In [25]:
# Import libraries
import pandas as pd
import numpy as np

In [26]:
data = pd.read_csv('../dataSet/train.csv')

In [27]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [28]:
# Chuyển cột index thành cột chỉ giá trị trong dataframe
data = pd.read_csv('../dataSet/train.csv', index_col='Id')

In [29]:

data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [30]:
# Lệnh show ra những tên cột có trong dataframe

data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [31]:
feature = ['LotArea','YearBuilt','1stFlrSF','2ndFlrSF','FullBath','BedroomAbvGr','TotRmsAbvGrd']

### 3.Spliting dataset into X and Y

In [32]:
x = data[feature]
y = data['SalePrice']

In [33]:
x.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
Id,,,,,,,
1,8450,2003,856,854,2,3,8
2,9600,1976,1262,0,2,3,6
3,11250,2001,920,866,2,3,6
4,9550,1915,961,756,1,3,7
5,14260,2000,1145,1053,2,4,9

In [34]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

X, y -> X_train,y_train,x_valid, y_valid

In [35]:
from sklearn.model_selection import train_test_split
# import thư viện để chia dataset thành 2 phần để train và test
X_train, X_valid, y_train, y_valid = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=0)
# ramdom states dùng để fix làm cho mô hình ổn định hơn khi chạy đi chạy lại nhiều lần thì kết quả vẫn không thay đổi

In [36]:
X_train.shape

(1168, 7)

In [37]:
x.shape

(1460, 7)

In [38]:
data.shape

(1460, 80)

### Training machine learing model

In [39]:
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=1)

In [40]:
# Fit training data into model 
dt_model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=1)

In [42]:
# Dự đoán
y_preds = dt_model.predict(X_valid.head())

In [43]:
pd.DataFrame({'y': y_valid.head(),'y_preds': y_preds})

          y   y_preds
Id
530  200624  335000.0
492  133000  140200.0
460  110000  119000.0
280  192000  207500.0
656   88000  112000.0

In [44]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf__model = RandomForestRegressor(random_state=1)
rf__model.fit(X_train, y_train)

RandomForestRegressor(random_state=1)

In [45]:
rf_valid_preds = rf__model.predict(X_valid)

In [47]:
rf_valid_preds[:5]

array([271690., 155039., 122024., 188915.,  91147.])

### Model Evaluation