## Đọc file lịch thi

### Để lấy ra mã môn, tên môn, hình thức thi, khoa chủ trì

In [27]:
import pandas as pd

In [28]:
filePath = 'D://LichThiKTHPHK12NamHoc2023-2024Tuan41-43(chinhthuc).xlsx'
df = pd.read_excel(filePath, keep_default_na=False)

`Bắt đầu xử lý để tạo ra một dataframe tiêu chuẩn`

In [29]:
df.head()

,TRƯỜNG ĐẠI HỌC DUY TÂN,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,NĂM HỌC 2023-2024,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,PHÒNG ĐÀO TẠO,,,,,,,"LỊCH THI KTHP HỌC KỲ 1, 2 - TUẦN 41--43 (C...",,,,,,,,,
1,,,,,,,,(TT KHẢO THÍ PHỐI HỢP VỚI CÁC ĐƠN VỊ LIÊN...,,,,,,,,,
2,STT,Thứ,Ngày thi,Giờ \nthi,Mã ngành,Mã số,Mã môn,Môn thi,Hình thức thi,Khối thi,Lần\n thi,SL \nPhòng,SL SV,Phòng thi,Địa điểm,Khoa chủ trì,Ghi chú
3,Lịch thi lại học kỳ 1 (2023-2024) - Danh sách ...,,,,,,,,,,,,,,,,
4,1,3,2024-05-28 00:00:00,09h30,IS-CS,412,IS-CS 412,Introduction to Cloud Computing,"Trắc nghiệm + Tự luận, Phòng LT",IS-CS 412 (AIS),1,1,3,801A,254 Nguyễn Văn Linh,Trường ĐTQT,

In [30]:
df = df.iloc[2:].reset_index(drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 580 entries, 0 to 579
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   TRƯỜNG ĐẠI HỌC DUY TÂN  580 non-null    object
 1   Unnamed: 1              580 non-null    object
 2   Unnamed: 2              580 non-null    object
 3   Unnamed: 3              580 non-null    object
 4   Unnamed: 4              580 non-null    object
 5   Unnamed: 5              580 non-null    object
 6   Unnamed: 6              580 non-null    object
 7    NĂM HỌC 2023-2024      580 non-null    object
 8   Unnamed: 8              580 non-null    object
 9   Unnamed: 9              580 non-null    object
 10  Unnamed: 10             580 non-null    object
 11  Unnamed: 11             580 non-null    object
 12  Unnamed: 12             580 non-null    object
 13  Unnamed: 13             580 non-null    object
 14  Unnamed: 14             580 non-null    object
 15  Unnamed: 15             580 non-null    object
 16  Unnamed: 16             580 non-null    object
dtypes: object(17)
memory usage: 77.2+ KB

In [31]:
df.columns = df.iloc[0]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 580 entries, 0 to 579
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STT              580 non-null    object
 1   Thứ              580 non-null    object
 2   Ngày thi         580 non-null    object
 3   Giờ
thi         580 non-null    object
 4   Mã ngành         580 non-null    object
 5   Mã số            580 non-null    object
 6   Mã môn           580 non-null    object
 7   Môn thi          580 non-null    object
 8   Hình thức thi  580 non-null    object
 9   Khối thi         580 non-null    object
 10  Lần
 thi         580 non-null    object
 11  SL
Phòng        580 non-null    object
 12  SL SV            580 non-null    object
 13  Phòng thi        580 non-null    object
 14  Địa điểm         580 non-null    object
 15  Khoa chủ trì     580 non-null    object
 16  Ghi chú          580 non-null    object
dtypes: object(17)
memory usage: 77.2+ KB

In [32]:
df = df.iloc[1:].reset_index(drop=True)
df.head()

,STT,Thứ,Ngày thi,Giờ \nthi,Mã ngành,Mã số,Mã môn,Môn thi,Hình thức thi,Khối thi,Lần\n thi,SL \nPhòng,SL SV,Phòng thi,Địa điểm,Khoa chủ trì,Ghi chú
0,Lịch thi lại học kỳ 1 (2023-2024) - Danh sách ...,,,,,,,,,,,,,,,,
1,1,3,2024-05-28 00:00:00,09h30,IS-CS,412,IS-CS 412,Introduction to Cloud Computing,"Trắc nghiệm + Tự luận, Phòng LT",IS-CS 412 (AIS),1,1,3,801A,254 Nguyễn Văn Linh,Trường ĐTQT,
2,Lịch thi học kỳ 2 (2023-2024),,,,,,,,,,,,,,,,
3,1,3,2024-05-28 00:00:00,07h30,MKT,364,MKT 364,Quảng Cáo & Chiêu Thị,"Tự luận, Phòng LT",MKT 364 (J-L-R-T-V-X),1,30,722,208(4)-213-214-307-308-313-314-401-407-408-414...,254 Nguyễn Văn Linh,QTKD,
4,2,3,2024-05-28 00:00:00,07h30,AET,497,AET 497,Đồ án CDIO,"Vấn đáp, Phòng LT",AET 497 (B-J),1,3,61,901A-902-903,254 Nguyễn Văn Linh,Cơ Khí,

In [34]:
df = df.drop([0,2])
df.head()

,STT,Thứ,Ngày thi,Giờ \nthi,Mã ngành,Mã số,Mã môn,Môn thi,Hình thức thi,Khối thi,Lần\n thi,SL \nPhòng,SL SV,Phòng thi,Địa điểm,Khoa chủ trì,Ghi chú
1,1,3,2024-05-28 00:00:00,09h30,IS-CS,412,IS-CS 412,Introduction to Cloud Computing,"Trắc nghiệm + Tự luận, Phòng LT",IS-CS 412 (AIS),1,1,3,801A,254 Nguyễn Văn Linh,Trường ĐTQT,
3,1,3,2024-05-28 00:00:00,07h30,MKT,364,MKT 364,Quảng Cáo & Chiêu Thị,"Tự luận, Phòng LT",MKT 364 (J-L-R-T-V-X),1,30,722,208(4)-213-214-307-308-313-314-401-407-408-414...,254 Nguyễn Văn Linh,QTKD,
4,2,3,2024-05-28 00:00:00,07h30,AET,497,AET 497,Đồ án CDIO,"Vấn đáp, Phòng LT",AET 497 (B-J),1,3,61,901A-902-903,254 Nguyễn Văn Linh,Cơ Khí,
5,3,3,2024-05-28 00:00:00,07h30,MTH,103,MTH 103,Toán Cao Cấp A1,"Trắc nghiệm + Tự luận, Phòng LT",MTH 103 (B-D-F-H-J-L-N-P-R),1,36,853,Tòa nhà E (204-205-301-304-401-402-404-405-501...,Hòa Khánh Nam,MT & KHTN,
6,4,3,2024-05-28 00:00:00,07h30,MIB,251,MIB 251,Căn Bản Vi Sinh Học,"Trắc nghiệm + Tự luận, Phòng LT",MIB 251 (B-D),1,8,173,Tòa nhà F (108-112-201-205-210-211-404),Hòa Khánh Nam,Y,

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 577 entries, 1 to 578
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STT              577 non-null    object
 1   Thứ              577 non-null    object
 2   Ngày thi         577 non-null    object
 3   Giờ
thi         577 non-null    object
 4   Mã ngành         577 non-null    object
 5   Mã số            577 non-null    object
 6   Mã môn           577 non-null    object
 7   Môn thi          577 non-null    object
 8   Hình thức thi  577 non-null    object
 9   Khối thi         577 non-null    object
 10  Lần
 thi         577 non-null    object
 11  SL
Phòng        577 non-null    object
 12  SL SV            577 non-null    object
 13  Phòng thi        577 non-null    object
 14  Địa điểm         577 non-null    object
 15  Khoa chủ trì     577 non-null    object
 16  Ghi chú          577 non-null    object
dtypes: object(17)
memory usage: 81.1+ KB

In [36]:
df1 = df.loc[:,['Mã ngành','Mã số','Mã môn','Môn thi','Hình thức thi','SL SV','Khoa chủ trì']]
df1.head()

,Mã ngành,Mã số,Mã môn,Môn thi,Hình thức thi,SL SV,Khoa chủ trì
1,IS-CS,412,IS-CS 412,Introduction to Cloud Computing,"Trắc nghiệm + Tự luận, Phòng LT",3,Trường ĐTQT
3,MKT,364,MKT 364,Quảng Cáo & Chiêu Thị,"Tự luận, Phòng LT",722,QTKD
4,AET,497,AET 497,Đồ án CDIO,"Vấn đáp, Phòng LT",61,Cơ Khí
5,MTH,103,MTH 103,Toán Cao Cấp A1,"Trắc nghiệm + Tự luận, Phòng LT",853,MT & KHTN
6,MIB,251,MIB 251,Căn Bản Vi Sinh Học,"Trắc nghiệm + Tự luận, Phòng LT",173,Y

In [38]:
x = df1.shape[0]
x

577

In [39]:
df1.dropna(inplace=True)
df1.shape[0]

577

In [41]:
df1.to_excel('subjectTitle.xlsx', index=False)

In [42]:
df1.to_csv('subjectTile.csv', index=False)